### ISSUE TITLE
Implement Async Storage for persistent local storage

### ISSUE THREAD

**Issue by HavaH123** [raghudevan/trackourspends#2]
using - https://facebook.github.io/react-native/docs/asyncstorage.html

Acceptance criteria;
- [x] load from local storage on user login -> dump to redux state
- [x] write to local storage when app close -> read from redux state

**Comment by raghudevan** [comment]
Can use https://facebook.github.io/react-native/docs/appstate.html to figure out when to write to `AsyncStorage`

**Comment by raghudevan** [comment]
In the local storage, we can store `{ user_id: user_state }` and when user logs in, retrieve `user_state` from the hash using `user_id`
